### ISSUE TITLE
Update the Readme to mention .tar and .tar.gz writing support

### ISSUE THREAD

**Issue by nvh** [nvh/NVHTarGzip#9]
This has been implemented in #6, but the Readme still doesn't reflect it

**Comment by nvh** [comment]
@rsanchezsaez Could you maybe take a look at this?

**Comment by rsanchezsaez** [comment]
Done in [PR #10](https://github.com/nvh/NVHTarGzip/pull/10). It also fixes a silly but critical bug with sync tarring, I suggest merging as soon as possible.

**Comment by nvh** [comment]
Thanks :tada:
